# Generated by Django 4.2.27 on 2026-01-04 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Asset name (e.g., 'EEUU', 'Europa')", max_length=100, unique=True)),
                ('symbol', models.CharField(blank=True, help_text='Optional symbol/ticker', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Portfolio name (e.g., 'Portfolio 1', 'Portfolio 2')", max_length=100, unique=True)),
                ('initial_value', models.DecimalField(decimal_places=2, default=1000000000.0, help_text='Initial portfolio value V₀ in dollars', max_digits=15)),
                ('initial_date', models.DateField(default=datetime.date(2022, 2, 15), help_text='Initial date (15/02/22)')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, help_text='Price date')),
                ('price', models.DecimalField(decimal_places=2, help_text='Asset price p_{i,t}', max_digits=15)),
                ('asset', models.ForeignKey(help_text='Related asset', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolios.asset')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_weight', models.DecimalField(decimal_places=6, help_text='Initial weight w_{i,0} as decimal (e.g., 0.15 for 15%)', max_digits=10)),
                ('asset', models.ForeignKey(help_text='Related asset', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_weights', to='portfolios.asset')),
                ('portfolio', models.ForeignKey(help_text='Related portfolio', on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Weight',
                'verbose_name_plural': 'Portfolio Weights',
                'ordering': ['portfolio', 'asset'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, help_text='Holding date')),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Quantity c_{i,t}', max_digits=20)),
                ('asset', models.ForeignKey(help_text='Related asset', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_holdings', to='portfolios.asset')),
                ('portfolio', models.ForeignKey(help_text='Related portfolio', on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Holding',
                'verbose_name_plural': 'Portfolio Holdings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, help_text='Transaction date')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], help_text='Transaction type: Buy or Sell', max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in dollars', max_digits=15)),
                ('asset', models.ForeignKey(help_text='Related asset', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolios.asset')),
                ('portfolio', models.ForeignKey(help_text='Related portfolio', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['portfolio', 'date'], name='portfolios__portfol_212a11_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['asset', 'date'], name='portfolios__asset_i_2b7aca_idx'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('asset', 'date'), name='unique_asset_date_price'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='price_positive'),
        ),
        migrations.AddConstraint(
            model_name='portfolioweight',
            constraint=models.UniqueConstraint(fields=('portfolio', 'asset'), name='unique_portfolio_asset_weight'),
        ),
        migrations.AddConstraint(
            model_name='portfolioweight',
            constraint=models.CheckConstraint(check=models.Q(('initial_weight__gte', 0), ('initial_weight__lte', 1)), name='weight_range_0_to_1'),
        ),
        migrations.AddIndex(
            model_name='portfolioholding',
            index=models.Index(fields=['portfolio', 'asset', 'date'], name='portfolios__portfol_a976b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolioholding',
            constraint=models.UniqueConstraint(fields=('portfolio', 'asset', 'date'), name='unique_portfolio_asset_date_holding'),
        ),
        migrations.AddConstraint(
            model_name='portfolioholding',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='quantity_non_negative'),
        ),
    ]
